# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'openFile_interface.ui'
#
# Created: Fri Sep 20 00:24:22 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 390)
        MainWindow.setMaximumSize(QtCore.QSize(440, 390))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_principal = QtGui.QFrame(self.centralwidget)
        self.frame_principal.setGeometry(QtCore.QRect(20, 20, 401, 281))
        self.frame_principal.setMaximumSize(QtCore.QSize(405, 500))
        self.frame_principal.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_principal.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_principal.setObjectName("frame_principal")
        self.buttonBox = QtGui.QDialogButtonBox(self.frame_principal)
        self.buttonBox.setGeometry(QtCore.QRect(220, 220, 166, 25))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.label_titulo = QtGui.QLabel(self.frame_principal)
        self.label_titulo.setGeometry(QtCore.QRect(0, 50, 401, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_titulo.setFont(font)
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.frame_titulo = QtGui.QFrame(self.frame_principal)
        self.frame_titulo.setGeometry(QtCore.QRect(130, 40, 141, 41))
        self.frame_titulo.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_titulo.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_titulo.setObjectName("frame_titulo")
        self.label_CampObrig = QtGui.QLabel(self.frame_principal)
        self.label_CampObrig.setGeometry(QtCore.QRect(10, 250, 301, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_CampObrig.setFont(font)
        self.label_CampObrig.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_CampObrig.setObjectName("label_CampObrig")
        self.layoutWidget = QtGui.QWidget(self.frame_principal)
        self.layoutWidget.setGeometry(QtCore.QRect(13, 100, 381, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_openFile = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_openFile.setFont(font)
        self.label_openFile.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_openFile.setObjectName("label_openFile")
        self.gridLayout.addWidget(self.label_openFile, 0, 0, 1, 1)
        self.lineEdit_fileName = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_fileName.setObjectName("lineEdit_fileName")
        self.gridLayout.addWidget(self.lineEdit_fileName, 0, 1, 1, 1)
        self.label_1_asterisco = QtGui.QLabel(self.layoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(34, 31, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 31, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(144, 141, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_1_asterisco.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_1_asterisco.setFont(font)
        self.label_1_asterisco.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1_asterisco.setObjectName("label_1_asterisco")
        self.gridLayout.addWidget(self.label_1_asterisco, 0, 2, 1, 1)
        self.Button_openFile = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.Button_openFile.setFont(font)
        self.Button_openFile.setObjectName("Button_openFile")
        self.gridLayout.addWidget(self.Button_openFile, 0, 3, 1, 1)
        self.label_pastaSaida = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_pastaSaida.setFont(font)
        self.label_pastaSaida.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_pastaSaida.setObjectName("label_pastaSaida")
        self.gridLayout.addWidget(self.label_pastaSaida, 1, 0, 1, 1)
        self.lineEdit_pastaSaida = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_pastaSaida.setObjectName("lineEdit_pastaSaida")
        self.gridLayout.addWidget(self.lineEdit_pastaSaida, 1, 1, 1, 1)
        self.label_2_asterisco = QtGui.QLabel(self.layoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(34, 31, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 31, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(144, 141, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_2_asterisco.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2_asterisco.setFont(font)
        self.label_2_asterisco.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2_asterisco.setObjectName("label_2_asterisco")
        self.gridLayout.addWidget(self.label_2_asterisco, 1, 2, 1, 1)
        self.Button_pastaSaida = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.Button_pastaSaida.setFont(font)
        self.Button_pastaSaida.setObjectName("Button_pastaSaida")
        self.gridLayout.addWidget(self.Button_pastaSaida, 1, 3, 1, 1)
        self.frame_rodape = QtGui.QFrame(self.centralwidget)
        self.frame_rodape.setGeometry(QtCore.QRect(20, 310, 401, 31))
        self.frame_rodape.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_rodape.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_rodape.setObjectName("frame_rodape")
        self.label_rodape = QtGui.QLabel(self.frame_rodape)
        self.label_rodape.setGeometry(QtCore.QRect(0, 0, 401, 31))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_rodape.setFont(font)
        self.label_rodape.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rodape.setObjectName("label_rodape")
        #MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 440, 25))
        self.menubar.setObjectName("menubar")
        #MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Gerador XML", None, QtGui.QApplication.UnicodeUTF8))
        self.label_titulo.setText(QtGui.QApplication.translate("MainWindow", "Ferramenta", None, QtGui.QApplication.UnicodeUTF8))
        self.label_CampObrig.setText(QtGui.QApplication.translate("MainWindow", "(*) - Campos Obrigatórios!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_openFile.setText(QtGui.QApplication.translate("MainWindow", "Ficheiro Entrada (.psd):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_1_asterisco.setText(QtGui.QApplication.translate("MainWindow", "(*)", None, QtGui.QApplication.UnicodeUTF8))
        self.Button_openFile.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_pastaSaida.setText(QtGui.QApplication.translate("MainWindow", "Ficheiro de Saida (.txt):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2_asterisco.setText(QtGui.QApplication.translate("MainWindow", "(*)", None, QtGui.QApplication.UnicodeUTF8))
        self.Button_pastaSaida.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rodape.setText(QtGui.QApplication.translate("MainWindow", "Ferramenta - Carlos Palma - António Baião", None, QtGui.QApplication.UnicodeUTF8))

